"""Column contracts and table ordering for the staging rebuild.

Keeping these contracts in one module makes it easier to compare the Python
loader with database migrations when table shapes change.
"""

from __future__ import annotations

RAW_TABLES = ("matches", "events", "lineups", "staff", "officials", "stats")

STAGING_RELOAD_ORDER = ("events", "lineups", "staff", "officials", "stats", "matches")
STAGING_INSERT_ORDER = ("matches", "events", "lineups", "staff", "officials", "stats")

RAW_REQUIRED_COLUMNS: dict[str, set[str]] = {
    "matches": {
        "match_id",
        "match_url",
        "season",
        "date",
        "home_team",
        "away_team",
        "home_score",
        "away_score",
    },
    "events": {"event_row_key", "match_id", "season", "event_index", "event_type"},
    "lineups": {"lineup_row_key", "match_id", "season", "team_side", "team_name", "player_name"},
    "staff": {"staff_row_key", "match_id", "season", "team_side", "team_name", "person_name"},
    "officials": {"official_row_key", "match_id", "season", "role", "official_name"},
    "stats": {"stat_row_key", "match_id", "season", "statistic_name"},
}


STAGING_COLUMNS: dict[str, tuple[str, ...]] = {
    "matches": (
        "match_id",
        "match_url",
        "source_season",
        "season",
        "match_date",
        "match_time",
        "league",
        "match_day",
        "home_team",
        "home_team_url",
        "away_team",
        "away_team_url",
        "ground_name",
        "ground_address",
        "man_of_the_match",
        "man_of_the_match_team",
        "home_score",
        "away_score",
        "total_goals",
        "goal_difference",
        "result",
        "winner_team",
        "is_forfeit",
        "is_administrative_result",
        "administrative_result_type",
        "administrative_note",
        "played_on_pitch",
        "home_awarded_points",
        "away_awarded_points",
        "is_source_anomaly",
        "source_anomaly_reason",
        "home_first_half_goals",
        "away_first_half_goals",
        "home_second_half_goals",
        "away_second_half_goals",
        "timeline_status",
        "timeline_issue_count",
        "timeline_note",
        "scoreline_goal_count",
        "timeline_goal_count",
        "stats_assist_count",
        "timeline_assist_count",
        "stats_yellow_card_count",
        "timeline_yellow_card_count",
        "stats_red_card_count",
        "timeline_red_card_count",
        "has_timeline",
        "has_lineups",
        "has_officials",
        "has_stats",
        "raw_ingested_at",
    ),
    "events": (
        "event_row_key",
        "match_id",
        "match_url",
        "source_season",
        "season",
        "match_date",
        "match_time",
        "league",
        "match_day",
        "home_team",
        "away_team",
        "event_index",
        "event_type",
        "event_minute_text",
        "minute_base",
        "minute_added",
        "minute_total",
        "is_added_time",
        "minute_period",
        "team_side",
        "team_name",
        "player_name",
        "player_url",
        "goal_type",
        "sub_out_player_name",
        "sub_out_player_url",
        "sub_in_player_name",
        "sub_in_player_url",
        "is_goal",
        "is_yellow_card",
        "is_red_card",
        "is_substitution",
        "raw_ingested_at",
    ),
    "lineups": (
        "lineup_row_key",
        "match_id",
        "match_url",
        "source_season",
        "season",
        "match_day",
        "home_team",
        "away_team",
        "team_name",
        "team_side",
        "squad_role",
        "shirt_number",
        "player_name",
        "player_url",
        "player_position",
        "is_player_of_match",
        "swap_badge_type",
        "linked_player_name",
        "linked_shirt_number",
        "raw_ingested_at",
    ),
    "staff": (
        "staff_row_key",
        "match_id",
        "match_url",
        "source_season",
        "season",
        "match_day",
        "home_team",
        "away_team",
        "team_name",
        "team_side",
        "role",
        "person_name",
        "person_url",
        "raw_ingested_at",
    ),
    "officials": (
        "official_row_key",
        "match_id",
        "match_url",
        "source_season",
        "season",
        "match_day",
        "home_team",
        "away_team",
        "role",
        "official_name",
        "raw_ingested_at",
    ),
    "stats": (
        "stat_row_key",
        "match_id",
        "match_url",
        "source_season",
        "season",
        "match_day",
        "home_team",
        "away_team",
        "statistic_name",
        "home_value",
        "away_value",
        "raw_ingested_at",
    ),
}

